version: "3.14"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: IT4320-Reservations
    ports:
      - "8001:8000"
    volumes:
      - .:/project
    environment:
      FLASK_ENV: development